---
- name: Make sure we have a wheel group
  listen: 'wheel group'
  group:
    name: wheel
    state: present

- name: Allow wheel group to have passwordless sudo
  listen: 'wheel group'
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
